#!/bin/bash

if [ ! -f /etc/bacula/initialized ]
then
  export >/etc/bacula/exports
  cp /create_postgresql_database /etc/bacula/scripts/
  cp /make_postgresql_tables /etc/bacula/scripts
  cd /etc/bacula/scripts
  ./create_postgresql_database 2>&1 >/var/log/create_result
  ./make_postgresql_tables 2>&1 >/var/log/make_result
  touch /etc/bacula/initialized
fi

supervisorctl start baculadir
supervisorctl start baculasd
