#!/bin/sh
#
# Copyright (C) 2000-2015 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
# Make full release
#

# Source config
. ./config

echo "Creating release version: ${ver}"

cd $cwd

./makebacularel $bacula $remote $branch $ver
./makedocsrel $bacula $docs $remote $branch $ver
